import lifeSkillCertificatePdf from '../assets/documents/ChungChi_Kỹ năng sống_1785826618265.pdf?url';

export const certificates = [
  {
    id: 'life-skill-certificate',
    title: 'Chứng chỉ Kỹ năng sống',
    course: 'Kỹ năng sống',
    studentName: 'Minh Anh',
    issueDate: '04/08/2026',
    score: 'Hoàn thành',
    issuer: 'Di-Ichi English Center',
    status: 'Đã cấp',
    description: 'Chứng chỉ ghi nhận quá trình hoàn thành chương trình kỹ năng sống và các hoạt động thực hành trong khóa học.',
    previewUrl: lifeSkillCertificatePdf,
    downloadUrl: lifeSkillCertificatePdf,
    fileName: 'ChungChi_Kỹ năng sống_1785826618265.pdf',
  },
  {
    id: 'a2-explorer-certificate',
    title: 'A2 Explorer Certificate',
    course: 'Explorer English A2',
    studentName: 'Minh Anh',
    issueDate: '12/07/2026',
    score: 'Excellent',
    issuer: 'Di-Ichi English Center',
    status: 'Đã cấp',
    description: 'Chứng chỉ ghi nhận học viên hoàn thành lộ trình Explorer English A2 với kết quả nổi bật về từ vựng, ngữ pháp và giao tiếp.',
    previewUrl: lifeSkillCertificatePdf,
    downloadUrl: lifeSkillCertificatePdf,
    fileName: 'A2_Explorer_Certificate.pdf',
  },
  {
    id: 'speaking-star-award',
    title: 'Speaking Star Award',
    course: 'Speaking Club Junior',
    studentName: 'Minh Anh',
    issueDate: '26/06/2026',
    score: 'Top 10%',
    issuer: 'Di-Ichi English Center',
    status: 'Đã cấp',
    description: 'Chứng nhận dành cho học viên có phần thể hiện speaking nổi bật, tự tin trình bày và phản hồi tốt trong hoạt động nhóm.',
    previewUrl: lifeSkillCertificatePdf,
    downloadUrl: lifeSkillCertificatePdf,
    fileName: 'Speaking_Star_Award.pdf',
  },
];
