export const courses = [
  {
    id: 'explorer-english-a2',
    title: 'Explorer English A2',
    teacher: 'Ms. Jenny',
    progress: 68,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=700&q=80',
    tag: 'Đang học',
    nextLesson: 'Past Simple Story',
    schedule: 'Thứ 2, 4 - 08:30',
    duration: '12 tuần',
    level: 'A2',
    description: 'Khóa học giúp học sinh củng cố ngữ pháp nền tảng, mở rộng từ vựng theo chủ đề và luyện phản xạ giao tiếp qua các hoạt động kể chuyện, nghe hiểu và dự án nhỏ.',
    outcomes: ['Kể lại trải nghiệm bằng Past Simple', 'Tự tin hỏi đáp trong tình huống quen thuộc', 'Hoàn thành bài đọc và nghe cấp độ A2'],
    lessons: [
      { title: 'Hello Friends', status: 'Hoàn thành', minutes: 35 },
      { title: 'My Family', status: 'Hoàn thành', minutes: 40 },
      { title: 'Past Simple Story', status: 'Đang học', minutes: 45 },
      { title: 'Amazing Places', status: 'Sắp mở', minutes: 40 },
    ],
    resources: ['Unit 6 Vocabulary PDF', 'Listening Track 06', 'Grammar Recap Slide'],
  },
  {
    id: 'teen-ielts-foundation',
    title: 'Teen IELTS Foundation',
    teacher: 'Mr. Daniel',
    progress: 42,
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=700&q=80',
    tag: 'Mới mở',
    nextLesson: 'Listening Mini Test',
    schedule: 'Thứ 3, 5 - 14:00',
    duration: '16 tuần',
    level: 'Foundation',
    description: 'Lộ trình nhập môn IELTS dành cho học sinh tuổi teen, tập trung vào kỹ năng nghe, đọc nhanh, vốn từ học thuật cơ bản và cách làm bài có chiến lược.',
    outcomes: ['Nắm cấu trúc bài thi IELTS', 'Luyện nghe ý chính và chi tiết', 'Viết đoạn văn ngắn có luận điểm rõ ràng'],
    lessons: [
      { title: 'IELTS Roadmap', status: 'Hoàn thành', minutes: 45 },
      { title: 'Reading Skimming', status: 'Hoàn thành', minutes: 50 },
      { title: 'Listening Mini Test', status: 'Đang học', minutes: 35 },
      { title: 'Writing Simple Opinion', status: 'Sắp mở', minutes: 55 },
    ],
    resources: ['Listening Mini Test', 'Academic Word List', 'Writing Template'],
  },
  {
    id: 'speaking-club-junior',
    title: 'Speaking Club Junior',
    teacher: 'Ms. Anna',
    progress: 83,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=700&q=80',
    tag: 'Sắp hoàn thành',
    nextLesson: 'Show and Tell',
    schedule: 'Thứ 7 - 09:00',
    duration: '8 tuần',
    level: 'Junior',
    description: 'Câu lạc bộ nói giúp học sinh luyện phát âm, trình bày ý tưởng và phản hồi bạn học trong môi trường thân thiện, nhiều trò chơi và hoạt động nhóm.',
    outcomes: ['Thuyết trình ngắn 2-3 phút', 'Phản hồi ý kiến của bạn bằng câu hoàn chỉnh', 'Cải thiện phát âm và ngữ điệu'],
    lessons: [
      { title: 'My Favorite Thing', status: 'Hoàn thành', minutes: 30 },
      { title: 'Team Interview', status: 'Hoàn thành', minutes: 35 },
      { title: 'Show and Tell', status: 'Đang học', minutes: 40 },
      { title: 'Final Speaking Day', status: 'Sắp mở', minutes: 45 },
    ],
    resources: ['Speaking Examples Video', 'Pronunciation Drill', 'Show and Tell Checklist'],
  },
];
