import paintPracticeDocx from '../assets/documents/CDS_K1_TH11_T1 THỰC HÀNH VẼ TRÊN PAINT (TIẾT 2).docx?url';
import paintPracticePdf from '../assets/documents/CDS_K1_TH11_T1 THỰC HÀNH VẼ TRÊN PAINT (TIẾT 2).pdf?url';
import fallingApplesPptx from '../assets/documents/Falling Apples.pptx?url';
import canvaIntroVideo from '../assets/documents/video_giới thiệu giao diện canva video.mp4?url';

export const materialFilters = ['Tất cả', 'PDF', 'Word', 'Video', 'Slide'];

export const materialLessons = [
  {
    id: 'paint-practice-lesson',
    title: 'Chủ đề 11 - Thực hành vẽ trên Paint',
    course: 'Tin học cơ bản',
    teacher: 'Di-Ichi Center',
    description: 'Bài học thực hành thao tác vẽ, chỉnh sửa và hoàn thiện sản phẩm đơn giản trong Paint.',
    duration: '45 phút',
    materialCount: 2,
  },
  {
    id: 'canva-interface-lesson',
    title: 'Làm quen công cụ Canva',
    course: 'Thiết kế cơ bản',
    teacher: 'Di-Ichi Center',
    description: 'Bài học giới thiệu giao diện Canva và các khu vực công cụ thường dùng khi thiết kế.',
    duration: '30 phút',
    materialCount: 1,
  },
  {
    id: 'interactive-slide-lesson',
    title: 'Slide tương tác Falling Apples',
    course: 'Thiết kế bài giảng',
    teacher: 'Di-Ichi Center',
    description: 'Bài học minh họa cách sử dụng slide tương tác để tăng sự tham gia trong lớp.',
    duration: '35 phút',
    materialCount: 1,
  },
];

export const materials = [
  {
    id: 'paint-practice-pdf',
    lessonId: 'paint-practice-lesson',
    type: 'PDF',
    title: 'Thực hành vẽ trên Paint - Tiết 2',
    course: 'Tin học cơ bản',
    teacher: 'Di-Ichi Center',
    lesson: 'Chủ đề 11 - Thực hành',
    size: 'Tài liệu PDF',
    updatedAt: '04/08/2026',
    icon: 'FileText',
    color: 'text-[#EF4444]',
    description: 'Tài liệu hướng dẫn học sinh thực hành vẽ trên Paint với các thao tác cơ bản và bài tập theo tiết học.',
    tags: ['Paint', 'Thực hành', 'Tin học'],
    previewType: 'pdf',
    previewUrl: paintPracticePdf,
    downloadUrl: paintPracticePdf,
    fileName: 'CDS_K1_TH11_T1 THỰC HÀNH VẼ TRÊN PAINT (TIẾT 2).pdf',
  },
  {
    id: 'paint-practice-word',
    lessonId: 'paint-practice-lesson',
    type: 'Word',
    title: 'Thực hành vẽ trên Paint - Bản Word',
    course: 'Tin học cơ bản',
    teacher: 'Di-Ichi Center',
    lesson: 'Chủ đề 11 - Thực hành',
    size: 'Tài liệu DOCX',
    updatedAt: '04/08/2026',
    icon: 'FileText',
    color: 'text-[#F97316]',
    description: 'Bản Word của tài liệu thực hành, phù hợp để giáo viên chỉnh sửa nội dung hoặc in phiếu bài tập.',
    tags: ['DOCX', 'Phiếu bài tập', 'Tin học'],
    previewType: 'docx',
    previewUrl: paintPracticePdf,
    downloadUrl: paintPracticeDocx,
    fileName: 'CDS_K1_TH11_T1 THỰC HÀNH VẼ TRÊN PAINT (TIẾT 2).docx',
  },
  {
    id: 'canva-interface-video',
    lessonId: 'canva-interface-lesson',
    type: 'Video',
    title: 'Video giới thiệu giao diện Canva',
    course: 'Thiết kế cơ bản',
    teacher: 'Di-Ichi Center',
    lesson: 'Làm quen công cụ Canva',
    size: 'Video MP4',
    updatedAt: '04/08/2026',
    icon: 'Video',
    color: 'text-[#2563EB]',
    description: 'Video hướng dẫn học sinh làm quen giao diện Canva, vị trí thanh công cụ và các thao tác cơ bản khi bắt đầu thiết kế.',
    tags: ['Canva', 'Video', 'Thiết kế'],
    previewType: 'video',
    previewUrl: canvaIntroVideo,
    downloadUrl: canvaIntroVideo,
    fileName: 'video_giới thiệu giao diện canva video.mp4',
  },
  {
    id: 'falling-apples-slide',
    lessonId: 'interactive-slide-lesson',
    type: 'Slide',
    title: 'Falling Apples',
    course: 'Thiết kế bài giảng',
    teacher: 'Di-Ichi Center',
    lesson: 'Slide tương tác',
    size: 'Tài liệu PPTX',
    updatedAt: '04/08/2026',
    icon: 'BookOpen',
    color: 'text-[#F59E0B]',
    description: 'Bài trình chiếu mẫu Falling Apples dùng để minh họa hoạt động tương tác trong lớp học.',
    tags: ['PPTX', 'Slide', 'Tương tác'],
    previewType: 'pptx',
    previewUrl: fallingApplesPptx,
    downloadUrl: fallingApplesPptx,
    fileName: 'Falling Apples.pptx',
  },
];
