export const quizzes = [
  {
    id: 'vocabulary-sprint',
    title: 'Vocabulary Sprint',
    course: 'Explorer English A2',
    teacher: 'Ms. Jenny',
    skill: 'Vocabulary',
    questions: 20,
    duration: '15 phút',
    score: '9.2',
    start: 'Sẵn sàng',
    difficulty: 'Dễ',
    attempts: 2,
    bestScore: '9.2',
    deadline: 'Hôm nay, 21:00',
    description: 'Ôn nhanh từ vựng Unit 6 qua câu hỏi chọn đáp án, ghép nghĩa và hoàn thành câu.',
    rules: ['Hoàn thành trong 15 phút', 'Không giới hạn chuyển câu', 'Có thể làm lại tối đa 3 lần', 'Điểm cao nhất sẽ được lưu'],
    topics: ['Travel words', 'Past tense verbs', 'Adjectives for places'],
    questionPreview: [
      { type: 'Multiple choice', prompt: 'Choose the word that means “chuyến phiêu lưu”.', points: 1 },
      { type: 'Fill in blank', prompt: 'Last weekend, we ____ a small museum.', points: 1 },
      { type: 'Matching', prompt: 'Match each adjective with the correct place.', points: 2 },
    ],
    examQuestions: [
      { id: 'q1', prompt: 'Choose the word that means “chuyến phiêu lưu”.', options: ['museum', 'adventure', 'ticket', 'guide'], answer: 'adventure' },
      { id: 'q2', prompt: 'Last weekend, we ____ a small museum.', options: ['visit', 'visited', 'visiting', 'visits'], answer: 'visited' },
      { id: 'q3', prompt: 'Which adjective best describes a very beautiful place?', options: ['boring', 'crowded', 'stunning', 'late'], answer: 'stunning' },
      { id: 'q4', prompt: 'A person who shows tourists around a place is a _____.', options: ['guide', 'pilot', 'chef', 'nurse'], answer: 'guide' },
      { id: 'q5', prompt: 'Choose the correct past form: take', options: ['taked', 'took', 'taken', 'takes'], answer: 'took' },
    ],
    history: [
      { date: '01/08/2026', score: '8.6', status: 'Đã hoàn thành' },
      { date: '03/08/2026', score: '9.2', status: 'Tốt nhất' },
    ],
  },
  {
    id: 'grammar-checkpoint',
    title: 'Grammar Checkpoint',
    course: 'Explorer English A2',
    teacher: 'Ms. Jenny',
    skill: 'Grammar',
    questions: 15,
    duration: '12 phút',
    score: 'Chưa có',
    start: 'Mở lúc 19:30',
    difficulty: 'Trung bình',
    attempts: 0,
    bestScore: '--',
    deadline: 'Hôm nay, 22:00',
    description: 'Kiểm tra nhanh Past Simple, câu phủ định, câu hỏi và trạng từ chỉ thời gian.',
    rules: ['Quiz mở theo lịch lớp', 'Mỗi câu có một đáp án đúng', 'Không xem đáp án trước khi nộp', 'Kết quả hiển thị ngay sau khi hoàn thành'],
    topics: ['Past Simple', 'Did questions', 'Negative sentences'],
    questionPreview: [
      { type: 'Multiple choice', prompt: 'Choose the correct past form of “go”.', points: 1 },
      { type: 'Error correction', prompt: 'Find the mistake: She didn’t went to school.', points: 2 },
      { type: 'Sentence order', prompt: 'Put the words in the correct order.', points: 2 },
    ],
    examQuestions: [
      { id: 'q1', prompt: 'Choose the correct past form of “go”.', options: ['goed', 'went', 'gone', 'goes'], answer: 'went' },
      { id: 'q2', prompt: 'Find the correct sentence.', options: ['She didn’t went home.', 'She didn’t go home.', 'She don’t went home.', 'She not go home.'], answer: 'She didn’t go home.' },
      { id: 'q3', prompt: 'Which word is often used with Past Simple?', options: ['now', 'every day', 'yesterday', 'usually'], answer: 'yesterday' },
      { id: 'q4', prompt: 'Make a question: you / watch / the movie?', options: ['Did you watched the movie?', 'Do you watched the movie?', 'Did you watch the movie?', 'Were you watch the movie?'], answer: 'Did you watch the movie?' },
      { id: 'q5', prompt: 'Choose the negative form: He played football.', options: ['He didn’t played football.', 'He didn’t play football.', 'He doesn’t played football.', 'He wasn’t play football.'], answer: 'He didn’t play football.' },
    ],
    history: [],
  },
  {
    id: 'listening-mini-test',
    title: 'Listening Mini Test',
    course: 'Teen IELTS Foundation',
    teacher: 'Mr. Daniel',
    skill: 'Listening',
    questions: 10,
    duration: '10 phút',
    score: '8.8',
    start: 'Làm lại',
    difficulty: 'Trung bình',
    attempts: 1,
    bestScore: '8.8',
    deadline: 'Ngày mai, 20:00',
    description: 'Luyện nghe ý chính và chi tiết với đoạn hội thoại ngắn theo dạng IELTS Foundation.',
    rules: ['Audio được nghe tối đa 2 lần', 'Không tua audio khi đang làm bài', 'Nên dùng tai nghe', 'Có review đáp án sau khi nộp'],
    topics: ['Main idea', 'Specific information', 'Number and date recognition'],
    questionPreview: [
      { type: 'Short answer', prompt: 'What time does the class start?', points: 1 },
      { type: 'Multiple choice', prompt: 'Where will the students meet?', points: 1 },
      { type: 'Form completion', prompt: 'Complete the missing phone number.', points: 2 },
    ],
    examQuestions: [
      { id: 'q1', prompt: 'The speaker says the class starts at _____.', options: ['8:15', '8:30', '9:00', '9:15'], answer: '8:30' },
      { id: 'q2', prompt: 'Where will the students meet?', options: ['Library', 'Room 204', 'Main hall', 'Cafeteria'], answer: 'Room 204' },
      { id: 'q3', prompt: 'What should students bring?', options: ['Dictionary', 'Headphones', 'Laptop', 'Notebook'], answer: 'Headphones' },
      { id: 'q4', prompt: 'The topic of the recording is mostly about _____.', options: ['travel plans', 'class instructions', 'sports events', 'food orders'], answer: 'class instructions' },
      { id: 'q5', prompt: 'The phone number ends in _____.', options: ['246', '426', '642', '624'], answer: '246' },
    ],
    history: [
      { date: '02/08/2026', score: '8.8', status: 'Đã hoàn thành' },
    ],
  },
];
